[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]
aptPkgs = ["php8.3-gd", "php8.3-mysql", "php8.3-zip", "php8.3-xml", "php8.3-mbstring", "php8.3-curl"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-req=ext-gd"]

[phases.build]
cmds = ["composer dump-autoload --optimize"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"